name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask gunicorn

    - name: Build and deploy
      run: |
        echo "web: gunicorn app:app" > Procfile
        git add Procfile
        git commit -m "Add Procfile for deployment"
        git push
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote add heroku https://git.heroku.com/your-app-name.git
        git push heroku main
